### ISSUE TITLE
Library Storage

### ISSUE THREAD

**Issue by Behemyth** [Synodic-Software/Soul-Engine#101]
Figure out the best way to store libraries. Currently, the user has to download the proper libraries and place them into `/Libraries`. What is the best alternative if CMake is our build system? Git LFS, Git submodules, an external cloud storage site are all alternatives.

**Comment by ferria** [comment]
How often would you want to update these version of a library used by the engine?

**Comment by ferria** [comment]
Also do you plan on increasing the number of libraries going forward?

**Comment by Behemyth** [comment]
Both would be a yes. Longest time without an update would be a year. Shortest may be every 3 months.

**Comment by ferria** [comment]
Based on the reading I've done so far: there is no pip, Maven, or Gradle for C++.  There are a couple of attempts but even they only have some of the libraries we need.  I wish there was a better option, but I think submodules in a `Libraries/[win,nix]/*` directory with possibly a python script for updating will end up being the best option.  CMake could then be pointed to the appropriate directory based on platform.

**Comment by Behemyth** [comment]
Should the implementation of creating this module be in this same issue or a new one?

**Comment by ferria** [comment]
Probably a new issue.  Close this issue then?
