### ISSUE TITLE
Dependency Management - Git Submodules

### ISSUE THREAD

**Issue by ferria** [Synodic-Software/Soul-Engine#105]
This will be a general issue for the implementation via Git Submodules as discussed in #101.  Windows support will be the first priority, followed by other platforms such as Linux.  Submodules will be in a `Libraries/[win,nix]/dependency` directory.  While the initial effort will involve manually downloading the dependencies, a Python (or similar language) script may eventually be added to help automate downloads.

**Comment by ferria** [comment]
Good to close @Behemyth ?

**Comment by Behemyth** [comment]
Good to close!
