### ISSUE TITLE
Create Platform Identification

### ISSUE THREAD

**Issue by Behemyth** [Synodic-Software/Soul-Engine#175]
Create two files `Sorce/System/Platform.h/.cpp` that use compile time identification to select a proper platform. If you are on Windows, it should selected `Windows` or some other enumerated type. Create an enumerated list of platforms to track. As a last resort preprocessor commands such as `#ifdef _win32` and the variety should be used.

**Comment by yichuan99** [comment]
The preprocessor flag can be a starting point. Below are two sites that provide comprehensive lists of preprocessor OS flags. 

https://sourceforge.net/p/predef/wiki/OperatingSystems/
http://www.boost.org/doc/libs/1_58_0/libs/predef/doc/html/predef/reference/boost_os_operating_system_macros.html

**Comment by yichuan99** [comment]
The preprocessor macro method will be used.

**Comment by Behemyth** [comment]
Merged
