### ISSUE TITLE
Logo proposal: Soul-Engine

### ISSUE THREAD

**Issue by baranpirincal** [Synodic-Software/Soul-Engine#201]
Hello! I examined your project and I can contribute on your project with making logo design. I am graphic designer and my main goal is make my portfolio better with supporting open source projects. If you interested and if your project has no logo design yet we can talk about design decisions. I am waiting your feedback, have a nice day!

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by Behemyth** [comment]
Thank you for the offer @baranpirincal but we have plans for a logo in the works. It's super awesome to see you go around and engaging the open source community.

Good luck with the portfolio!
