### ISSUE TITLE
Add Code of Conduct and Contributing Guidelines

### ISSUE THREAD

**Issue by kburk1997** [Synodic-Software/Soul-Engine#222]
**Before submitting a request make sure you check the following**
- [X] I've attached the relevant labels
- [X] I've looked at the other issues and this feature does not exist

After reviewing your proposal and documentation, I noticed:

- Your project doesn't have a Code of Conduct. 
- Contributing guidelines are incomplete

In order to foster a welcoming and inclusive community, RCOS adopted a Code of Conduct in Spring 2018. Beginning fall 2018, projects are **required** to have a project-specific Code of Conduct that is compatible with the RCOS Community Code of Conduct.

Templates that are compatible with the RCOS Community Code of Conduct include:
- [our Code of Conduct template](https://github.com/rcos/rcos-handbook/blob/master/docs/community/code_of_conduct_template.md) -- tailored specifically for RCOS projects
- [the Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) -- widely adopted in open source (and in fact was one of our starting points for the RCOS code of conduct)

Your proposal's Team Policies are a good place to start for Contributing Guidelines. I would recommend adding a modified version of your team policies, including links to ZenHub and possibly improving readability (I noticed long chunks of text which may not format well in Markdown).

**Comment by Behemyth** [comment]
Thank you for the suggestions! Both have been added, however incomplete they may be.
