### ISSUE TITLE
Failing to open file in VulkanShader::CreateModule

### ISSUE THREAD

**Issue by benjaminrsherman** [Synodic-Software/Soul-Engine#230]

**Comment by Behemyth** [comment]
Ok, your going to have to compile the shaders for your system`Soul Engine\Resources\Shaders`

**Comment by Behemyth** [comment]
Feel free to organize and update the [Wiki](https://github.com/Synodic-Software/Soul-Engine/wiki) if you think it would help other in this process.

**Comment by benjaminrsherman** [comment]
The issue was caused by not building SoulEditor in a `build` subdirectory.
