### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by Behemyth** [Synodic-Software/Soul-Engine#41]
A website is needed for this project which can automatically build and display Doxygen generated code. Additionally, module documentation (in the form of a webpage) that is hand created would override the Doxygen content, allowing high quality documentation to exist where effort is applied, and a backup where it is not.

**Comment by ferria** [comment]
Maybe use Github pages for simplicity?

**Comment by Behemyth** [comment]
Github pages would be good for the short term, but not for the long term with the current administrative plans.
