### ISSUE TITLE
Create cmakelists.txt

### ISSUE THREAD

**Issue by Behemyth** [Synodic-Software/Soul-Engine#43]
Create a cross-platform build solution for all operating systems and all building tool flavors with Cmake. Target all recent build tools and do not worry about backwards compatibility. For example, Visual Studio 2017, not 2015.

**Comment by ferria** [comment]
Which C++ standard should I target: 11, 14, or 17?

**Comment by ferria** [comment]
Also, I see that there is currently a small cmakelists.txt file in dev, what needs to be added/changed?

**Comment by Behemyth** [comment]
Target is c++17. Talk to @eti-yen about what he has done. The end goal is to get a building and compiling project on all platforms.
