### ISSUE TITLE
Design Tagged Heap

### ISSUE THREAD

**Issue by Behemyth** [Synodic-Software/Soul-Engine#94]
Design the tagged heap to implement tags, heaps, and blocks of data revolving around the CPU architecture.

**Comment by lsilvestro96** [comment]
Designing the new memory manager using a tagged heap is complete. A UML diagram describing the basic class structure can be found here: https://repository.genmymodel.com/lsilvestro96/TaggedHeap.

**Comment by Behemyth** [comment]
Awesome! Onward to implementation.
